[project]
name = "afrecord-win"
version = "0.1.1"
description = "Record sound in cli in windows"
readme = "README.md"
authors = [{name = "Sukhbinder Singh"}]
license = {text = "Apache-2.0"}
requires-python = ">=3.8"
classifiers = [
    "License :: OSI Approved :: Apache Software License"
]
dependencies = []

[project.urls]
Homepage = "https://github.com/sukhbinder/afrecord-win"
Changelog = "https://github.com/sukhbinder/afrecord-win/releases"
Issues = "https://github.com/sukhbinder/afrecord-win/issues"
CI = "https://github.com/sukhbinder/afrecord-win/actions"

[project.scripts]
afrecord = "afrecord_win.cli:cli"

[project.optional-dependencies]
test = ["pytest"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
